spring.application.name=ai-chatbot
spring.ai.openai.api-key = {openAPIKey}
spring.ai.openai.chat.model = gpt-3.5-turbo
spring.ai.stabilityai.api-key = {stabilityAIKey}
# Force the auto-configuration to use a valid Engine ID
spring.ai.stabilityai.image.options.model=stable-diffusion-xl-1024-v1-0